version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - pubsub

  kafka1:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9093,PLAINTEXT://18.189.110.78:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
    networks:
      - pubsub

  kafka2:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9094,PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9094,PLAINTEXT://18.189.110.78:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
    networks:
      - pubsub

  kafka3:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9095:9092"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9095,PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka3:9095,PLAINTEXT://18.189.110.78:9095
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
    networks:
      - pubsub

  pubsub:
    image: kbenellisjsu/pubsub-system:latest
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    environment:
      KAFKA_BROKER: kafka1:9092,kafka2:9094,kafka3:9095
      KAFKA_EXTERNAL_BROKER: 18.189.110.78:9092,18.189.110.78:9094,18.189.110.78:9095
      KAFKAJS_NO_PARTITIONER_WARNING: "1"
    networks:
      - pubsub

networks:
  pubsub:
    driver: overlay
