version: "3.8"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ALLOW_ANONYMOUS_LOGIN: "yes" # Allow unauthenticated users to connect
    networks:
      - pubsub

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # External port for Kafka to be accessible outside Docker (host)
      - "9093:9093" # Internal Kafka port, used inside Docker network
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,PLAINTEXT://0.0.0.0:9092 # Listeners for internal and external communication
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,PLAINTEXT://localhost:9092 # Advertised listeners for Docker network and external clients
      KAFKA_LISTENER_NAMES: INSIDE,PLAINTEXT # Both INSIDE and PLAINTEXT listeners
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_INTERNAL: INSIDE
      KAFKA_LISTENER_INTERNAL_PORT: 9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT # Define security protocols for both listeners
    networks:
      - pubsub

  pubsub:
    image: kbenellisjsu/pubsub-system:latest
    build: .
    ports:
      - "3000:3000" # Expose your app on port 3000
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9093 # Internal Docker network Kafka address
      KAFKA_EXTERNAL_BROKER: localhost:9092 # External Kafka broker accessible from the host
      KAFKAJS_NO_PARTITIONER_WARNING: "1" # Suppress partitioner warning from kafkajs
    networks:
      - pubsub

networks:
  pubsub:
    driver: overlay
