version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ALLOW_ANONYMOUS_LOGIN: "yes"  # Allow unauthenticated users to connect
    networks:
      - pubsub-system

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"  # Expose Kafka broker to the host
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,PLAINTEXT://localhost:9093  # Add PLAINTEXT for external access
      KAFKA_LISTENER_NAMES: INSIDE,PLAINTEXT
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_NAME_PLAINTEXT: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_INTERNAL: INSIDE
      KAFKA_LISTENER_INTERNAL_PORT: 9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT  # Define security protocol for both listeners
    networks:
      - pubsub-system

  pubsub-system:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9093  # Broker address for internal communication within Docker network
      KAFKA_EXTERNAL_BROKER: localhost:9093  # Use this for external communication
      KAFKAJS_NO_PARTITIONER_WARNING: "1"  # Suppress partitioner warning
    networks:
      - pubsub-system

networks:
  pubsub-system:
    driver: bridge
